version: 1.0.{build}
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore SharpDXLab\SharpDXLab.sln

build:
  project: SharpDXLab\SharpDXLab.sln
  verbosity: minimal

after_build:
  - echo %APPVEYOR_REPO_NAME%
